### ISSUE TITLE
Wrong Link for Jike repost

### ISSUE THREAD

**Issue by sxzz** [NaturalSelectionLabs/Web3Pass#292]
**Describe the bug**
Jike repost link is `https://web.okjike.com/repost/id`, not `https://web.okjike.com/originalPost/id`

https://github.com/NaturalSelectionLabs/Cheers/blob/bafeca2c5859e17e693b8140afa9d8b81b3bbad9/src/views/Home.vue#L818-L820

**To Reproduce**

My Cheers Page: https://cheers.bio/sanxiaozhizi.bit

I have a Jike repost: 

> Coding is legislating.
> RT 方的胖虎: Coder is lawyer."

It linked to `https://web.okjike.com/originalPost/62434430e8de690010dd9123`, and the correct link is `https://web.okjike.com/repost/62434430e8de690010dd9123`

**Expected behavior**

Link is correct for reposts.

**Screenshots**

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/6481596/161286674-8dc1b689-c80b-4287-bd65-f6dada38b018.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

I think maybe RSS3 should add post type (`originalPost` / `repost`) to payload.

BTW, there's the same problem in Revery.

**Comment by yzhe819** [comment]
Thanks for your help 💖. Fixed in #296

**Comment by sxzz** [comment]
You can try my Cheers profile. The issue still exists.

IMHO, Jike has two post type `originalPost` and `repost`. Changing the `originalPost` to `repost` directly will make the forwarded post work , but normal post can't work.
